### ISSUE TITLE
I can read but not create

### ISSUE THREAD

**Issue by JMFUZ** [WoolDoughnut310/micropython-firebase-auth#1]
Hi,
I'm trying this library and fth firebase-firestore one.
I can connect to my database because I can read
But I can't write in it and I've no error message, then I can't know why

Firestore rules : 

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{user} {
      allow read, write: if request.auth != null;
    }
  }
}

My code : 

import os 
import network
import time
import ujson, urequests, _thread

SSID = "SSID"
password = "password"
wlan = network.WLAN(network.STA_IF)
wlan.active(True)

if not wlan.isconnected():
    wlan.connect(SSID, password)
    print("Attente de la connexion WIFI", end="...")
    while not wlan.isconnected():
        print(".", end="")
        time.sleep(1)
    print()
    
print("Reseau WIFI", SSID , "connecté :", wlan.ifconfig()[0])

import ufirestore as firestore
from json import FirebaseJson
from firebase_auth import FirebaseAuth
from firebase_auth import AuthSession

firestore.set_project_id("firestore-db-test1")

auth = FirebaseAuth("API_KEY")
auth.sign_in("mail@gmail.com", "AAAAAAA")

firestore.set_access_token(auth.session.access_token)

print("===== Lecture =====")
print("")
raw_doc = firestore.get("users/")
print("raw_doc : ", raw_doc)
print("")

print("===== Ecriture =====")
print("")
doc = FirebaseJson()
doc.set("Name/stringValue", "John Doe")
doc.set("Age/integerValue", 25)

response = firestore.create("users/", doc, bg=False)
print(response)

auth.sign_out()

The results : 

===== Lecture =====

raw_doc :  {'documents': [{'fields': {'Age': {'stringValue': '21'}, 'Name': {'stringValue': 'Jane Doe'}}, 'createTime': '2022-10-31T12:32:34.756017Z', 'name': 'projects/firestore-db-test1/databases/(default)/documents/users/FhjDBdURqcaQlpwdXlFG', 'updateTime': '2022-10-31T12:32:34.756017Z'}]}

===== Ecriture =====

Traceback (most recent call last):
  File "<stdin>", line 92, in <module>
  File "ufirestore.py", line 222, in create
  File "ufirestore.py", line 90, in create
  File "ufirestore.py", line 53, in send_request
  File "urequests.py", line 104, in request
AssertionError: 

I need help because I really don't know I happened

Thanks in advance

**Comment by rhylkiio** [comment]
Hello, I am facing the same problem here except I can't read or write. Were you able to find a way around it

Traceback (most recent call last):
  File "<stdin>", line 57, in <module>
  File "<stdin>", line 37, in connect_to_wifi
  File "<stdin>", line 18, in connect_to_firebase
  File "/lib/ufirestore/ufirestore.py", line 229, in get
  File "/lib/ufirestore/ufirestore.py", line 104, in get
  File "/lib/ufirestore/ufirestore.py", line 51, in send_request
TypeError: unexpected keyword argument 'params'

**Comment by JMFUZ** [comment]
Could you give me your code of the send_request function?Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : rhylkiio ***@***.***> Date : 22/06/2023  11:08  (GMT+01:00) À : WoolDoughnut310/micropython-firebase-auth ***@***.***> Cc : JMFUZ ***@***.***>, Author ***@***.***> Objet : Re: [WoolDoughnut310/micropython-firebase-auth] I can read but not create (Issue #1) 
Hello, I am facing the same problem here except I can't read or write. Were you able to find a way around it
Traceback (most recent call last):
File "", line 57, in 
File "", line 37, in connect_to_wifi
File "", line 18, in connect_to_firebase
File "/lib/ufirestore/ufirestore.py", line 229, in get
File "/lib/ufirestore/ufirestore.py", line 104, in get
File "/lib/ufirestore/ufirestore.py", line 51, in send_request
TypeError: unexpected keyword argument 'params'

**Comment by rhylkiio** [comment]
Hello, I found my problem wasn't with this firebase-auth library but with micropython-firebase-firestore. I posted in the wrong forum.
My create method still has an issue I can't create a document on Firestore but I have been able to read documents.I am trying to implement some of the solutions in this thread: https://github.com/WoolDoughnut310/micropython-firebase-firestore/issues/5
Please let me know if you succeed in creating a document.
To solve your issue remove the "params argument" in send request. Here is my updated send request code:

```
def send_request(path, method="get", params=dict(), data=None, dump=True):
    headers = {}

    if FIREBASE_GLOBAL_VAR.ACCESS_TOKEN:
        headers["Authorization"] = "Bearer " + FIREBASE_GLOBAL_VAR.ACCESS_TOKEN

    response = urequests.request(
        method, path,headers=headers, json=data) #removed params argument

    if dump == True:
        if response.status_code < 200 or response.status_code > 299:
            print(response.text)
            raise FirestoreException(response.reason, response.status_code)

        json = response.json()
        if json.get("error"):
            error = json["error"]
            code = error["code"]
            message = error["message"]
            raise FirestoreException(message, code)
        return json

**Comment by rhylkiio** [comment]
Hello, I found the problem, to solve Modify your json.py def process function by commenting out the name. Here is the updated code :

``` 
def process(self, name):
        return {
           # "name": name,
            "fields": self.data
        }
